name: SignRank
main: me.coolblinger.signrank.SignRank
autthor: coolblinger
version: 1.2.2
description: >
  A plugin that ranks up people after interacting with a sign.
permissions:
   signrank.build:
      description: Create SignRank signs
      default: op